server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://977685:glc_eyJvIjoiMTIwNDc0NCIsIm4iOiJzdGFjay0xMDE5OTA1LWludGVncmF0aW9uLW1pbmkyIiwiayI6ImtXOHBtVEc5N0gxakY3Qjk0cWM2QjQ2dSIsIm0iOnsiciI6InByb2Qtc2EtZWFzdC0xIn19@logs-prod-024.grafana.net/api/prom/push
        
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log